version: '3'
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
  chrome:
    image: selenium/node-chrome:latest
    volumes:
    - /dev/shm:/dev/shm
    - ./downloads:/home/seluser/Downloads
    depends_on:
    - selenium-hub
    environment:
    - HUB_HOST=selenium-hub
  firefox:
    image: selenium/node-firefox:latest
    shm_size: '512m'
    volumes:
    - /dev/shm:/dev/shm
    - ./downloads:/home/seluser/Downloads
    depends_on:
    - selenium-hub
    environment:
    - HUB_HOST=selenium-hub
  search-module:
    image: mayrloncarlos/selenium-docker
    depends_on:
    - chrome
    - firefox
    environment:
    - BROWSER=firefox
    - HUB_HOST=selenium-hub
    - MODULE=search-module.xml
    volumes:
    - ./output/search-result:/usr/share/udemy/test-output
  book-flight-module:
    image: mayrloncarlos/selenium-docker
    depends_on:
    - chrome
    - firefox
    environment:
    - BROWSER=chrome
    - HUB_HOST=selenium-hub
    - MODULE=book-flight-module.xml
    volumes:
    - ./output/book-result:/usr/share/udemy/test-output 